behaviors:
  Game:
    trainer_type: sac
    hyperparameters:
      batch_size: 32
      buffer_size: 50000
      learning_rate: 0.0003
      learning_rate_schedule: linear
      buffer_init_steps: 0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 550000
    time_horizon: 64
    summary_freq: 50000